### ISSUE TITLE
Share the Rust APFloat port with the Rust compiler.

### ISSUE THREAD

**Issue by eddyb** [stoklund/cretonne#136]
See rust-lang/rust#43554 for more details. We of course have to publish that crate on crates.io first.

Would be glad to hear what specific needs Cretonne has from software floating-point.

**Comment by stoklund** [comment]
This is a cool project, and if we need software floating point at compiler time, we should probably use this.

When compiling WebAssembly, the code generator is unlikely to discover opportunities for floating point constant folding that weren't already taken care of by LLVM when it generates the WASM. This makes FP constant folding a low priority at least until we start compiling WebAssembly that hasn't been properly optimized.

When JIT-compiling, we also need to make sure that we are bit-exact with the other tiers. Since WebAssembly floating point permits some non-determinism around NaN's, we should probably avoid constant-folding any FP expressions yielding NaN results.

Given this restriction, and given that we only need f32 and f64, it is possible that we can use the host's hardware FP for constant folding. That would be preferable in terms of compiler code size, performance, and dependency management.

**Comment by sunfishcode** [comment]
Closing -- If Cretonne needs software floating-point code in the future, we should definitely look into sharing the APFloat code!
