### ISSUE TITLE
Regalloc assertion failure: Couldn't clear fixed output interference

### ISSUE THREAD

**Issue by sunfishcode** [stoklund/cretonne#175]
```
test regalloc
set is_64bit=1
isa intel haswell

function %test(i64) -> i64 native {
ebb0(v0: i64):
    v2 = iconst.i64 12
    v5 = udiv v0, v2
    v6 = iconst.i64 13
    v9 = udiv v0, v6
    v10 = iadd v5, v9
    return v10
}
```

FAIL x.cton: panicked in worker #0: Couldn't clear fixed output interference for v2

**Comment by stoklund** [comment]
Thanks, I'll take a look.

**Comment by stoklund** [comment]
Hmm, the `x86_udivmodx.i64` instrution has two fixed inputs and two fixed outputs:

```
# XX /n for division: inputs in %rax, %rdx, r. Outputs in %rax, %rdx.
div = TailRecipe(
        'div', Ternary, size=1,
        ins=(GPR.rax, GPR.rdx, GPR), outs=(GPR.rax, GPR.rdx),
        emit='''
        PUT_OP(bits, rex1(in_reg2), sink);
        modrm_r_bits(in_reg2, bits, sink);
        ''')
```

With a tied output register, the spiller is responsible for ensuring that the input value is killed at the instruction, but for a fixed output that happens to coincide with a fixed input, the spiller does nothing.

We need some way of having fixed *and* tied operands so the spiller knows it needs to break the interference.

[This kind of two-address interference is handled in the spiller because it can increase register pressure which the spiller needs to know about.]
