### ISSUE TITLE
Would a "no-std" support be possible as a future feature?

### ISSUE THREAD

**Issue by lachlansneff** [stoklund/cretonne#198]
I can think of a number of projects that execute in environments without a stdlib, but still require the ability to JIT or AOT compile wasm or something similar into native code.

Is this something that would be possible as a future feature?

**Comment by sunfishcode** [comment]
The core cretonne code generator crate has minimal dependencies, and very likely could be made to work with just libcore and liballoc, which should be feasible in many limited environments.

My understanding is that full no_std excludes liballoc though, which would rule out featues like `Vec`, which would require extensive invasive changes, though I'd be happy to be corrected.

**Comment by lachlansneff** [comment]
The environment that I'd be using does indeed have access to `liballoc`, so that's not a roadblock for me, but it may be for other projects. The largest obstruction that I've run into in adapting other crates to work without `libstd` is that `liballoc` does not have the `HashMap` type.

If I fork cretonne and submit a pull request with a `no_std` feature, will you consider merging it?

**Comment by sunfishcode** [comment]
Ah, I wasn't aware that `HashMap` is not in liballoc. Cretonne codegen does use `HashMap` for some things. What are the options for converting code that uses it to no_std?

@stoklund may want to chime in here, but I'd be in favor of merging a no-std patch if it doesn't negatively impact Cretonne's other use cases, and doesn't make the code significantly harder to maintain.

**Comment by lachlansneff** [comment]
There is a `core_collections` crate with supposedly exposes `HashMap` without `stdlib`. I was unable to get it to work through.

It wouldn't be overly difficult to write a type that proxies to `HashMap` when `stdlib` is available and has it's own, simplistic implementation otherwise.

**Comment by stoklund** [comment]
It could make sense for us to support a more restricted environment. Some requirements are:

- Cretonne currently builds on stable Rust, and it should stay that way.
- Using Cretonne in a normal Rust environment should be unaffected.
- Performance must be unaffected.

I am also concerned about how this affects maintenance of our current code and how it impedes development of new code.

It seems clear that we can't use a pure `no_std` environment, so how do we define the minimal environment that Cretonne needs? This environment needs to be usable by more than one external project.

**Comment by lachlansneff** [comment]
I haven't done anything with features in Rust before, so I'm not sure how it would affect code quality. Since many projects do have a `no_std` feature or the equivalent, I'm guessing that it does not negatively affect maintainability or modularity of the code base.

I think the minimum environment for code generation without `stdlib` would have `liballoc` and a working global allocator implementation.

Execution of code would require memory protection attributes (e.g. mprotect or equivalent), if that's part of cretonne.

**Comment by sunfishcode** [comment]
I look forward to seeing what it looks like! If you have any questions, please do ask (here, or file a new issue).

Cretonne is factored so that execution (and mprotect etc.) are not part of the core code generator crate, so embedded environments can provide their own code they need to get code executed.

**Comment by lachlansneff** [comment]
If I have questions or need to discuss something that fits more with the style of a chatroom, should I ask it on the mozilla `#cretonne` irc room?

**Comment by sunfishcode** [comment]
Yes, that works too.

**Comment by lachlansneff** [comment]
Sweet. Thanks for you help. I'll close this issue and if need be, I'll open another.

**Comment by stoklund** [comment]
Thanks for implementing this over in #204. That is very helpful.

Let me expand on the maintenance issues I mentioned above. @sunfishcode has already brought some of this up: It is one thing to get this feature working today, another to make sure that it keeps working as Cretonne evolves. To make sure that it stays working, we can (and should) document all the rules about which `std` modules can and can't be used etc, but `no_std` is still going to break almost instantly if the rules are not enforced automatically. Developers are only human, and they don't read documentation until something appears broken.

So the rules need to be enforced by the `test-all.sh` script which is used both by CI and developers to run all the unit tests. This script needs to be as fast as possible since it is part of the developer workflow. The script already compiles everything twice much to my chagrin (for unit tests and for file tests), so adding a third compilation of everything is not very appealing. I also think it would be problematic to require Cretonne developers to have a nightly Rust installed. (Personally, I don't have a nightly Rust installation because the daily 100+ MB downloads are excessive for something I don't need.)

It is extremely important that it is easy to get started working on Cretonne.

So the question is, how do we make sure that this feature doesn't get broken immediately without putting an unreasonable burden on Cretonne developers?

**Comment by stoklund** [comment]
Regarding `HashMap`, Cretonne should probably have a pretty strict policy about using it outside testing code. The standard implementation has security features that prevents malicious data from causing a kind of DoS attack with deliberate hash collisions.

- If Cretonne is depending on these security features anywhere, that should be documented loudly, and it would be a very bad idea to swap in an alternative implementation that doesn't have the same security features.
- If Cretonne is *not* depending on the security features, we probably should not be using `HashMap` in the first place since the secure hash is very slow.

**Comment by bjorn3** [comment]
`liballoc` provides a `BTreeMap`, which could be used instead of `HashMap`

**Comment by sunfishcode** [comment]
Would it be feasible to add a feature named something like "nonsecure_hashmaps", and then have no-std builds fail compilation with a helpful message if this feature isn't enabled? 

In the future, we could use such a feature to also control whether we switch to `fnv` hashing in std-enabled builds (which I expect we'll want eventually).

That way, the high-level model is:
 - Cretonne's default is a std build that includes the std security measures
 - Users can enable features to opt out of some of these measures
 - Some features conflict with or require other features

**Comment by lachlansneff** [comment]
Okay, so how about we create a Map type that has a set api for cretonne to use, then depending on features, we can have that type use `HashMap`, `BTreeMap`, or something else?

**Comment by sunfishcode** [comment]
Can we keep the code itself using `HashMap`, but just change whether that ends up using `std::collections::HashMap` or `hashmap_core::HashMap`?

**Comment by lachlansneff** [comment]
@sunfishcode Yep, that's definitely possible.
