### ISSUE TITLE
FYI: Travis CI has non-uniform CPUs, some pre-haswell

### ISSUE THREAD

**Issue by pchickey** [stoklund/cretonne#237]
Just noting this because I spent a few days on-and-off trying to figure out a bug.

We're generating (and then running) Cretonne code on Travis-CI, using cretonne-native to get the ISA. We discovered that some of the build machines have pre-haswell CPUs, flags below. This means functions with lzcnt or the bmi instructions will fail during codegen with an error like `Verifier(Error { location: inst106, message: "v94 is a ghost value used by a real [RexOp1jmpb#eb] instruction" })` - this is a known bug because those encodings aren't supported yet, of course.

I dont believe Cretonne actually executes any generated code on Travis CI at this time, but its something to keep in mind.

```
[intel]
has_sse2 = true
has_sse3 = true
has_ssse3 = false
has_sse41 = true
has_sse42 = true
has_popcnt = true
has_avx = true
has_bmi1 = false
has_bmi2 = false
has_lzcnt = false
```

**Comment by stoklund** [comment]
Thanks!

By design, the tests run by `test-all.sh` do not depend on the specific CPU architecture they're running on, precisely to avoid these kinds of issues. If you find any cases where that's not true, please let me know.

A Mozilla contributor is working on pre-Haswell implementations of the `ctz` and `clz` instructions which should give us support back to Nehalem.

**Comment by pchickey** [comment]
Excellent - I think Nehalem is as old as we need. And yes, I like that there's nothing dependent on the host CPU in test-all.
